### ISSUE TITLE
The dialog new post will not appear on the /user page if the logged-in user is not the same.

### ISSUE THREAD

**Issue by reymondjulio** [reymondjulio/friendbook#16]
The issue that hasn't been resolved because I can't understand the logic flow yet

**Comment by mhaidarhanif** [comment]
```tsx
const isSameUser = user.username === userDatabase.username
const isOwner = user.username === userDatabase.username
```

**Comment by reymondjulio** [comment]
Finished the dialog new post will not appear on the /user page if the logged-in user is not the same.

https://github.com/reymondjulio/friendbook/blob/main/app/routes/%24username.tsx
